faster spd checking
geomstats/geomstats pull request #1143
Opened 2021-09-07 17:55 UTC by SaitejaUtpala

faster SPD checking by cholesky decomposition
- [ ] numpy
- [ ] autograd
- [ ] tensorflow
- [ ] pytorch

some benchmarks on numpy backend
|size |  geomstats time| new time|
|------| -------------------- | -----  |  
| (10, 2000, 2000) | 21 sec | 3sec |
| (100 , 1000, 1000) | 25 sec | 4 sec|
|  (1000, 200, 2000)  | 5 sec | ~0 sec |

2021-09-21 19:17 UTC, SaitejaUtpala commented
@SaitejaUtpala RTM

2021-09-22 16:08 UTC, ninamiolane requested changes
Very nice! Smart to have though about this, thank you! 🎉 

Did you check that this was leading to a speed-up in a 4 backends? I trust you with the benchmark.

Just one comment: would it make more sense to have the functions:
- _is_single_matrix_pd
- is_pd
*within* the geomstats core code base, in the `matrices.py` module, and only put the `gs.linalg.cholesky` function in the backends?

This way:
- we only put in the `_backend` folder the mapping between the functionalities from torch, tf, autograd and np,
- the logic that we use to perform computations is thus in the codebase, more visible
- we avoid copy-pasting code in the 3 backends as much as possible.

What do you think?

 Note: if you do put these functions in the core codebase, then the docstrings will need to be adapted to respect our conventions ;)

2021-12-15 16:16 UTC, SaitejaUtpala commented
@ninamiolane  I think we should keep _is_single_matrix_pd in the backends and move is_pd to the matrices module.. because currently I am using  torch.linalg.cholesky, but there is https://pytorch.org/docs/stable/generated/torch.linalg.cholesky_ex.html (still in experimental stage). but it can be even faster than torch.linalg.cholesky for pd checking ( quoting `This makes this function a faster way to check if a matrix is positive-definite, and it provides an opportunity to handle decomposition errors more gracefully or performantly than torch.linalg.cholesky() does.`)

2021-12-15 21:33 UTC, ninamiolane approved these changes
There are a few typos here and there: let's correct them and we can merge! great work!

2021-12-15 21:33 UTC, ninamiolane commented on geomstats/_backend/autograd/linalg.py
> +    positive definite
Missing .

2021-12-15 21:33 UTC, ninamiolane commented on geomstats/_backend/numpy/linalg.py
> +    positive definite
Missing .

2021-12-15 21:33 UTC, ninamiolane commented on geomstats/geometry/matrices.py
> +        is_pd : array-like, shape=[...,]
NIT: is_pd -> is_spd

2021-12-15 21:33 UTC, ninamiolane commented on tests/tests_geomstats/test_backends.py
> +    def test_is_singel_matrix_pd(self):
NIT: is_single

2021-12-15 23:15 UTC, ninamiolane approved these changes
Great, thank you!

2021-12-15 23:15 UTC, merged