clean test_symmetric_matrices
geomstats/geomstats pull request #1261
Opened 2021-12-28 20:09 UTC by SaitejaUtpala

cleaned tests in symmetric_matrices

2021-12-28 20:34 UTC, ninamiolane requested changes
Many thanks!! 🙌 High-level comments:
- should the "indirect" tests (such as projection_and_belongs, etc) be kept in their randomized version? I fear we might forget about them if we delete them in this PR.
- Some docstrings for contest.py would be helpful 🙏 
Looking perfect otherwise ! (Module our conversation about deepsource)

2021-12-28 20:34 UTC, ninamiolane commented on tests/conftest.py
> +random = pytest.mark.rt
Ooooh, it's pytest who calls random : rt?

2021-12-28 20:34 UTC, ninamiolane commented on tests/tests_geomstats/test_symmetric_matrices.py
> +    class TestingData(TestData):
TestingData(TestData) could be better named: how about
SymmetricMatricesData(TestData)?

2021-12-28 20:34 UTC, ninamiolane commented on tests/tests_geomstats/test_symmetric_matrices.py
> +    class TestingData(TestData):
TestingData(TestData) could be better named: how about
SymmetricMatricesData(TestData)?

2021-12-28 20:34 UTC, ninamiolane commented on tests/conftest.py
> +random = pytest.mark.rt
In this case, my bad, maybe all should be called "rt"

2021-12-28 20:34 UTC, ninamiolane commented on tests/conftest.py
> +import inspect
This module should have some docstrings, both at the top of the file, but also for the classes.

2021-12-28 22:25 UTC, SaitejaUtpala commented
> Many thanks!! raised_hands High-level comments:
> 
>     * should the "indirect" tests (such as projection_and_belongs, etc) be kept in their randomized version? I fear we might forget about them if we delete them in this PR.
> 
>     * Some docstrings for contest.py would be helpful pray
>       Looking perfect otherwise ! (Module our conversation about deepsource)

sure. I will add them randomized tests as well

2021-12-29 18:44 UTC, ninamiolane requested changes

2021-12-29 18:44 UTC, ninamiolane commented on tests/conftest.py
> +"""Pytest utility classes, functions and fixtures"""
Missing . and need a blank line after the module docstring? (I think? it would be good to get DeepSource back on track for these things).

2021-12-29 18:44 UTC, ninamiolane commented on tests/conftest.py
> +        Parameters:
Not geomstats conventions

2021-12-29 18:44 UTC, ninamiolane commented on tests/conftest.py
> +        """Wraps test data with corresponding markers.
Infinitive verbs in docstrings: Wraps -> Wrap

(DeepSource knows :p)

2021-12-29 18:44 UTC, ninamiolane commented on tests/conftest.py
> +    (except class methods and static methods). Two conventions have to followed
NIT: Small edits on the English syntax:

Two conventions need to be respected:

1) There should be a TestData object named 'testing_data'.
2) Every test function should have its corresponding data function inside TestData object. Ex:
      test_exp() should have method called exp_data() inside 'testing_data.'"""

2021-12-29 18:44 UTC, ninamiolane commented on tests/tests_geomstats/test_symmetric_matrices.py
> +        """Data class for Testing Symmetric Matrices"""
missing .

2021-12-29 18:59 UTC, ninamiolane approved these changes
Excellent!! 🎉 thank you @SaitejaUtpala !

2021-12-29 19:04 UTC, merged