waldspace without geometry, only space
geomstats/geomstats pull request #1351
Opened 2022-02-23 08:37 UTC by JonasLueg

Wald Space without geometry; compatible with all backends hopefully; added the minimum function to all backends.

2022-02-23 10:47 UTC, annacalissano requested changes
Jonas we need to add the docstring to each function describing the input and the outputs. The docstring should be in infinite tense not 3rd person. Some of the longer comments can be embedded into the docstring.

2022-02-23 10:47 UTC, annacalissano commented on geomstats/_backend/__init__.py
> +        "minimum",
wouah!

2022-02-23 10:47 UTC, annacalissano commented on geomstats/geometry/trees.py
> +for example.
BHV spaces as well? Are we going to use this class for the bhv or we are going to split it

2022-02-23 10:47 UTC, annacalissano commented on geomstats/geometry/trees.py
> +        # TODO: the parameter n could be dropped theoretically...
delete TODO

2022-02-23 10:47 UTC, annacalissano commented on geomstats/geometry/trees.py
> +        """ Determines if a subset is contained in either part of a split.
subset of leaves or of branches?

2022-02-23 10:47 UTC, annacalissano commented on geomstats/geometry/trees.py
> +        # make some assertions about the given parameters.
Leave the # comments only if explanatory of the code

2022-02-23 10:47 UTC, annacalissano commented on geomstats/geometry/trees.py
> +        # if partitions are not equal, then structures are not equal.
make this # comment into the function description

2022-02-23 10:47 UTC, annacalissano commented on geomstats/geometry/trees.py
> +        """ The (flat) vector containing the edge weights in Nye notation. """
Nye notation should be maybe substituted with a reference, otherwise if it is an internal lexicon we should better explain it

2022-02-23 10:47 UTC, annacalissano commented on geomstats/geometry/trees.py
> +        self._st: Structure = st
should we maybe call st structure, as it will be more self explanatory

2022-02-23 10:47 UTC, annacalissano commented on geomstats/geometry/trees.py
> +        # TODO use gs.fill_diagonal here, but it is not implemented yet
TODO delete or solve

2022-02-23 10:47 UTC, annacalissano commented on geomstats/geometry/waldspace.py
> +        self.a = spd.SPDMatrices(n=self.n)
should we call a differently, is it the paper notation?

2022-02-23 10:47 UTC, annacalissano commented on geomstats/geometry/waldspace.py
> +        def _to_forest(_point):
can we try to delete this extra step and make only one function to_forest?

2022-02-23 10:47 UTC, annacalissano commented on geomstats/geometry/waldspace.py
> +        """Check if a point `wald` belongs to Wald space.
we should refer it as point if it is the nomenclature of the input

2022-02-23 10:47 UTC, annacalissano commented on geomstats/geometry/waldspace.py
> +            """Checks if exists at least one split between each pair of labels."""
add docstring

2022-02-23 10:47 UTC, annacalissano commented on geomstats/geometry/waldspace.py
> +        def _delete_random_edges(splits, labels, probability):
Add docstring

2022-02-23 10:47 UTC, annacalissano commented on geomstats/geometry/waldspace.py
> +            """Generates a random wald."""
Add docstring

2022-02-23 10:47 UTC, annacalissano commented on geomstats/geometry/waldspace.py
> +    'https://stackoverflow.com/questions/38924421/is-there-a-standard-way-to-partition-a
refer to it as reference or in the see also section at the bottom of the docstring

2022-02-23 10:47 UTC, annacalissano commented on geomstats/geometry/waldspace.py
> +    """Computes the structure induced by a distance matrix, entries = inf possible."""
Add docstring

2022-02-23 10:47 UTC, annacalissano commented on geomstats/geometry/waldspace.py
> +    """Computes the split representation of a single tree characterized by a distance
Add docstring

2022-02-23 10:47 UTC, annacalissano commented on geomstats/geometry/waldspace.py
> +    # plan is the following:
maybe this longer comments could be insert in the docstring at the beginning of the class

2022-02-23 10:47 UTC, annacalissano commented on geomstats/geometry/waldspace.py
> +    """Gives back the supposed length of a split according to the dist matrix dist."""
Add docstring

2022-02-23 10:47 UTC, annacalissano commented on geomstats/geometry/trees.py
> +        """The restriction of a split to a subset, returns a split."""
Add docstring

2022-02-23 10:47 UTC, annacalissano commented on geomstats/geometry/trees.py
> +        """ Gives back the part of this split that is directed to the other split. """
other maybe it is not a good name, can we change to something else?

2022-02-23 10:47 UTC, annacalissano commented on geomstats/geometry/trees.py
> +        """ Gives back the part of this split that is directed to the other split. """
same for all other variable below

2022-04-08 21:16 UTC, JonasLueg commented
Yes, this PR is outdated. I have a stupid question: if we close the PR, nothing gets deleted in my repository, right?

2022-04-10 08:39 UTC, JonasLueg commented
Good, then I'll close it!

2022-04-10 08:39 UTC, closed without merging