refactor invariantt metric
geomstats/geomstats pull request #1374
Opened 2022-02-27 09:05 UTC by SaitejaUtpala

2022-03-09 18:49 UTC, ninamiolane commented
This PR does not pass the deep source test. Add a comment on why this can be ignored in this PR, or pass the tests before requesting a review.

2022-03-09 18:50 UTC, SaitejaUtpala commented
> This PR does not pass the deep source test. Add a comment on why this can be ignored in this PR, or pass the tests before requesting a review.

@ninamiolane  sorry. It's self issue that we cannot do anything right now.

2022-03-09 19:02 UTC, ninamiolane requested changes
Where is the codecoverage decrease coming from?

I also see many tests skipped: @nguigs what do you think, should these tests be skipped?

2022-03-09 23:02 UTC, SaitejaUtpala commented
@ninamiolane yup that is reason it is marked as draft. some tests were failing. I wanted to see if removing that would make difference.

2022-03-22 19:09 UTC, SaitejaUtpala commented
@ninamiolane ignore deep source and -0.05%, are skipped due to some constant failing. Thanks

2022-03-22 19:11 UTC, ninamiolane approved these changes
I will merge, but can you remove the leftover comment in the next PR? Thanks for this huge work!

2022-03-22 19:11 UTC, ninamiolane commented on tests/tests_geomstats/test_invariant_metric.py
> +    # skip_test_exp_belongs = True
leftover comment, which was also caught by deepsource.

2022-03-22 19:12 UTC, merged