Update PR_template
geomstats/geomstats pull request #1472
Opened 2022-04-09 04:02 UTC by monsij

Addresses #1208 
@ninamiolane , @chicken-biryani let me know if I am missing something !

2022-04-09 19:03 UTC, chicken-biryani requested changes

2022-04-09 19:03 UTC, chicken-biryani commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] My PR follows PEP8 guidelines (run '`flake8`)
The link to Pep8

2022-04-09 19:03 UTC, chicken-biryani commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] My PR follows PEP8 guidelines (run '`flake8`)
Comment about the commands to run can be added?
"$ pip3 install -r dev-requirements.txt
Then you can run the following two commands:

$ flake8 --ignore=D,W503,W504 geomstats examples tests
$ flake8 geomstats/geometry geomstats/learning"

2022-04-09 19:03 UTC, chicken-biryani commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] My code is properly documented and I made sure the documentation renders properly.
Link to the documentation style.

2022-04-10 22:05 UTC, ninamiolane commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] I have made sure the code passes all unit tests.
Great comments. Additionally, you can explain how to change the backend `export GEOMSTATS_BACKEND=pytorch` to test in pytorch, for example.

2022-04-10 22:08 UTC, ninamiolane reviewed
Thanks Monsij! A few comments

2022-04-10 22:08 UTC, ninamiolane commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] My pull request has a suggestive title.
"clear and explanatory" title

2022-04-10 22:08 UTC, ninamiolane commented on .github/PULL_REQUEST_TEMPLATE.md
> +<!-- Tell us which issue does this PR fix . Why is this feature implementation/fix is important in practice ?-->
typo: remove double "is"

2022-04-14 03:02 UTC, monsij commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] I have made sure the code passes all unit tests.
Added commented sections below checklist to make it concise !

2022-04-14 05:40 UTC, monsij commented
@ninamiolane @chicken-biryani changes made !

2022-04-14 14:32 UTC, ninamiolane approved these changes
LGTM, many thanks!

2022-04-14 14:32 UTC, merged