binomial and exponential distributions, update on base to integrate floats (?)
geomstats/geomstats pull request #1497
Opened 2022-04-14 09:57 UTC by Jules-Deschamps

## Description 

## Issue

## Addidtional context

2022-04-14 13:14 UTC, alebrigant requested changes
Great ! Just some last minor comments to address and we can merge.

2022-04-14 13:14 UTC, alebrigant commented on tests/data/binomial_data.py
> +            dict(n_draws=2, vec=-1.0, expected=False),
- `vec` is misleading as your are testing a point on the manifold and not a tangent vector. 
- Values higher than 1 are not tested.
- For one point, maybe test `gs.array([x])` as well as float `x`.
- Several points are not tested, i.e. `gs.array([x, y])` as well as `[x, y]` and `gs.array([[x],[y]])`.

2022-04-14 13:14 UTC, alebrigant commented on tests/data/exponential_data.py
> +        ]
Similar comments as for binomial.

2022-04-14 13:38 UTC, Jules-Deschamps commented on geomstats/geometry/base.py
> +        if self.shape[0] == 1 and len(point.shape) <= 1:
if is input an array that is already in the wanted form (eg for the dimension 1 exception we are dealing with, gs.array([[0],[1]]), deleting this condition would eventually return gs.array([0,1]) which is not what we want.
for all types of possible inputs in dimension 1 (ie float, gs.array(float), gs.array([float]), gs.array([float1, float2]), gs.array([[float1],[float2]])), belongs will "try its conditions" on gs.array([[float]]) for a single vector and for gs.array([[float1], [float2]]) for 2 vectors.

2022-04-14 13:42 UTC, Jules-Deschamps commented on geomstats/information_geometry/exponential.py
> +    i.e. the unit segment.
yes there have been some confusions between the two i will take care of it

2022-04-14 14:28 UTC, alebrigant commented on geomstats/information_geometry/binomial.py
> +    """
Remaining inversion in the docstrings : positive reals <-> unit interval.

2022-04-14 14:28 UTC, alebrigant commented on geomstats/information_geometry/binomial.py
> +    """
.. [AM1981] Atkinson, C., & Mitchell, A. F. (1981). Rao's distance measure.
    Sankhyā: The Indian Journal of Statistics, Series A, 345-365.

2022-04-14 14:28 UTC, alebrigant commented on geomstats/information_geometry/exponential.py
> +    i.e. the unit segment.
Remaining inversion unit segment <-> positive reals.

2022-04-14 14:28 UTC, alebrigant commented on geomstats/information_geometry/exponential.py
> +
.. [AM1981] Atkinson, C., & Mitchell, A. F. (1981). Rao's distance measure.
Sankhyā: The Indian Journal of Statistics, Series A, 345-365.

2022-04-14 14:28 UTC, alebrigant commented on tests/data/binomial_data.py
> +            dict(n_draws=2, vec=-1.0, expected=False),
`vec` -> `point`

2022-04-19 11:29 UTC, closed without merging

2022-04-19 11:30 UTC, Jules-Deschamps commented
doesn't work with new "triangle_dist" but close because of history issues