gamma distributions
geomstats/geomstats pull request #1523
Opened 2022-05-03 15:29 UTC by Jules-Deschamps

2022-05-18 10:00 UTC, alebrigant requested changes
Great work ! There is a lot of code to review, therefore a lot of comments. Mostly style though !

2022-05-18 11:45 UTC, Jules-Deschamps commented on geomstats/information_geometry/gamma.py
> +                    gamma.pdf(t, a=point[:, 0], scale=1 / point[:, 1])
You're right I was still in natural coordinates but it makes more sense if everything is in standard coordinates.

2022-05-18 14:30 UTC, alebrigant requested changes
Some more comments left to address !

2022-05-18 14:30 UTC, alebrigant commented on geomstats/information_geometry/gamma.py
> +    def natural_to_standard_point(self, point):
Remove '_point' in name to be consistent with Hypersphere.

2022-05-18 14:30 UTC, alebrigant commented on geomstats/information_geometry/gamma.py
> +    def standard_to_natural_point(self, point):
Ditto.

2022-05-18 14:30 UTC, alebrigant commented on geomstats/information_geometry/gamma.py
> +    def natural_to_standard_vec(self, vec, base_point):
Rename to `tangent_natural_to_standard` to be consistent with Hypersphere.

2022-05-18 14:30 UTC, alebrigant commented on geomstats/information_geometry/gamma.py
> +    def standard_to_natural_vec(self, point):
Ditto.

2022-05-18 14:30 UTC, alebrigant commented on geomstats/information_geometry/gamma.py
> +    Arwini, K. A., & Dodson, C. T. (2008). Information geometry (pp. 31-54).
This is still not in the same format as e.g. [here](https://github.com/geomstats/geomstats/blob/9bad7b8cc618fc0b9cc3dee13d01698a8f86bb11/geomstats/geometry/spd_matrices.py#L483). It must start with `.. [AD2008]` etc.

2022-05-18 14:30 UTC, alebrigant commented on geomstats/information_geometry/gamma.py
> +        Springer Berlin Heidelberg.
Same as previous comment.

2022-05-18 14:30 UTC, alebrigant commented on geomstats/information_geometry/gamma.py
> +        Guo, B. N., Qi, F., Zhao, J. L., & Luo, Q. M. (2015). Sharp inequalities for
Ditto.

2022-05-18 14:30 UTC, alebrigant commented on geomstats/information_geometry/gamma.py
> +        Guo, B. N., Qi, F., Zhao, J. L., & Luo, Q. M. (2015). Sharp inequalities for
Same as previous comments about reference format.

2022-05-18 14:30 UTC, alebrigant commented on geomstats/information_geometry/gamma.py
> +        method : string, {'geomstats', 'lsoda'}
Here I think `solver` would make more sense than `method`.

2022-05-18 14:30 UTC, alebrigant commented on geomstats/information_geometry/gamma.py
> +        solver="geodesic_shooting",
I think there was a mix up: here `method` makes more sense than `solver`, which refers to solving ODEs. See previous comment.

2022-05-19 07:39 UTC, alebrigant requested changes
Thanks for the modifications ! We're almost there: just a few more tests to add so that the coverage is good.

2022-05-19 07:39 UTC, alebrigant commented on tests/data/gamma_data.py
> +        )
Can we test both solvers with tangent vectors of different norms, not only lsoda ? And maybe select a norm randomly in a set of integers (e.g. `random.sample(range(1, 5))`) ?

2022-05-19 07:39 UTC, alebrigant commented on tests/data/gamma_data.py
> +        )
Same.

2022-05-19 07:39 UTC, alebrigant commented on tests/tests_geomstats/test_gamma.py
> +        self.assertAllClose(result, False)
Can we also test exp and log on points where the geodesic is known, or at least its shape ? e.g. if vertical lines are geodesics, then `exp` of a base point and a vertical vector should yield a point vertically aligned with the base point, and `log` of two vertically aligned points should yield a vertial vector.

2022-05-19 07:39 UTC, alebrigant commented on geomstats/information_geometry/gamma.py
> +    def _geodesic_ivp(self, initial_point, initial_tangent_vec, n_steps=N_STEPS):
This function should be tested, see e.g. [here](https://github.com/geomstats/geomstats/blob/9bad7b8cc618fc0b9cc3dee13d01698a8f86bb11/tests/tests_geomstats/test_dirichlet.py#L159).

2022-05-19 07:39 UTC, alebrigant commented on geomstats/information_geometry/gamma.py
> +    def _exp_ivp(self, tangent_vec, base_point, n_steps=N_STEPS):
This function should be tested.

2022-05-19 07:39 UTC, alebrigant commented on geomstats/information_geometry/gamma.py
> +    def _approx_geodesic_bvp(
This function should be tested, see e.g. [here](https://github.com/geomstats/geomstats/blob/9bad7b8cc618fc0b9cc3dee13d01698a8f86bb11/tests/tests_geomstats/test_dirichlet.py#L216).

2022-05-19 07:39 UTC, alebrigant commented on geomstats/information_geometry/gamma.py
> +    def _geodesic_bvp(
This function should be tested, see e.g. [here](https://github.com/geomstats/geomstats/blob/9bad7b8cc618fc0b9cc3dee13d01698a8f86bb11/tests/tests_geomstats/test_dirichlet.py#L167).

2022-05-19 07:39 UTC, alebrigant commented on geomstats/information_geometry/gamma.py
> +    def geodesic_vp(
Ditto.

2022-05-20 08:44 UTC, alebrigant requested changes
Last changes:
- add `test_log_after_exp`
- remove duplicates in random tests
- add a lower bound in `random_point` and use it to improve performance of test of horizontal geodesics
- other comments to be addressed are in the code.

2022-05-20 08:44 UTC, alebrigant commented on tests/data/gamma_data.py
> +                norm=random.choice(self.n_points_list),
Same.

2022-05-20 08:44 UTC, alebrigant commented on tests/data/gamma_data.py
> +                norm=random.choice(self.n_points_list),
Same.

2022-05-20 08:44 UTC, alebrigant commented on geomstats/information_geometry/gamma.py
> +    def geodesic_vp(
Rename to `_geodesic_vp`.

2022-05-23 09:17 UTC, merged