Make default_point_type a property
geomstats/geomstats pull request #1644
Opened 2022-09-16 12:44 UTC by lpereira95

This PR makes `default_point_dtype` a property (computed from shape).

`shape` has been corrected for several spaces and/or metrics and a general test to validate shape against the shape of a generated random point was added.

2022-09-16 14:36 UTC, lpereira95 commented
@ninamiolane failures are unrelated with this PR. In fact, the failure in the example is related with last release of matplotlib (to be address in another PR).

2022-09-16 16:26 UTC, ninamiolane requested changes

2022-09-16 16:26 UTC, ninamiolane commented on examples/plot_kmeans_manifolds.py
> +        point_type=manifold.coords_type,
Why the change of name?

point_type is a purely computational attribute, but coords_type often refers to why coordinate system can be used on a manifold, which is a mathematical attribute.

2022-09-16 16:31 UTC, ninamiolane commented on geomstats/geometry/_hyperbolic.py
> +    coords_type : str, {'extrinsic', 'intrinsic', etc}
Ah, never mind, this is indeed a coords_type 🤔

2022-09-16 16:31 UTC, ninamiolane commented on geomstats/geometry/hyperboloid.py
> +        # TODO: coords_type vs default_coords_type?
left over comment: address in this PR?

2022-09-16 16:31 UTC, ninamiolane commented on examples/plot_kmeans_manifolds.py
> +        point_type=manifold.coords_type,
Nevermind, it seems that point_type was wrongfully used here: it is indeed a coords_type

2022-09-16 16:32 UTC, ninamiolane commented
Great, thank you! Why not removing default_point_type and point_type completely? (instead of making it a property?)

It could be simpler to have only one variable ("shape") referring to that one concept.

2022-09-19 11:43 UTC, lpereira95 commented
I think it may be valuable to keep `default_point_type`, because its current use case is the bool `self.default_point_type == "vector"` or `self.default_point_type == "matrix"`, which in my opinion is more readable than `len(self.shape) == 1` or `len(self.shape)>1`. But if you think it is better to use `len(self.shape)`, it is completely fine to me.( Anyway, `default_point_type` is never assigned, except for the product manifold case.)

Regarding `default_point_type`/`point_type` and `default_coords_type`/`coords_type`, I think it needs homogenization (remove `default`?). I guess this naming exists due to some history and the distinction is not worthy anymore.

2022-09-21 12:53 UTC, merged