Add Poisson distributions and associated tests
geomstats/geomstats pull request #1785
Opened 2023-01-05 10:07 UTC by tramy1258

## Checklist

- [ ] My pull request has a clear and explanatory title.
- [ ] If necessary, my code is [vectorized](https://www.geeksforgeeks.org/vectorization-in-python/).
- [ ] I added appropriate unit tests.
- [ ] I made sure the code passes all unit tests. (refer to comment below)
- [ ] My PR follows [PEP8](https://peps.python.org/pep-0008/) guidelines. (refer to comment below)
- [ ] My PR follows [geomstats coding style](https://github.com/geomstats/geomstats/blob/master/docs/contributing.rst#coding-style-guidelines) and API.
- [ ] My code is properly documented and I made sure the documentation renders properly. ([Link](https://github.com/geomstats/geomstats/blob/master/docs/contributing.rst#documentation))
- [ ] I linked to issues and PRs that are relevant to this PR.

## Description

## Issue

## Additional context

2023-01-26 14:23 UTC, alebrigant requested changes
Nice ! Most comments concern the docstrings. I'm also not sure if the output shape of geodesics is right. The first dimension should always correspond to vectorization, so usually it is `[n_points, n_times, dim]`. Since here we are in dimension 1, is the output shape `[n_points, n_times, 1]` or `[n_points, n_times]` ?

2023-01-26 14:23 UTC, alebrigant commented on geomstats/information_geometry/poisson.py
> +            """
Same comments as for the geometric distributions: samples and not points representing Poisson distributions.

2023-01-26 14:23 UTC, alebrigant commented on geomstats/information_geometry/poisson.py
> +        """
Same comments as for geometric distributions.

2023-01-26 14:23 UTC, alebrigant commented on geomstats/information_geometry/geometric.py
> +            Point representing an geometric distribution (lambda parameter).
lambda is non standard for the parameter of a geometric distribution, I'm not sure it helps.

2023-01-26 14:23 UTC, alebrigant commented on tests/data/geometric_data.py
> +            )
What is this for ? Maybe add a word on this is the docstring of the test_data ?

2023-01-26 14:23 UTC, alebrigant commented on geomstats/information_geometry/geometric.py
> +            initial conditions.
Is the output shape of `geodesic` tested ? It should be enough to test the output shape of `_geodesic_ivp` and `_geodesic_bvp` through the shapes of `exp` and `log`, but I don't see these tests (test_exp_shape and test_log_shape) in the test file.

2023-01-27 14:38 UTC, tramy1258 commented on geomstats/information_geometry/geometric.py
> +            initial conditions.
Yes, the shapes are tested. In `test_geometric`, `TestGeometricMetric` inherits `RiemannianMetricTestCase` which inherits `ConnectionTestCase` which contains tests for `exp` and `log`. It is actually just the docstring that is incorrect.

2023-01-27 16:55 UTC, alebrigant approved these changes
Thanks for the changes ! Last very minor docstring changes and we are good to merge !

2023-01-27 16:55 UTC, alebrigant commented on geomstats/information_geometry/geometric.py
> +                Point representing an geometric distribution (lambda).
Replace also "Point representing a geometric distribution" by "Point in the sample space, i.e. an integer."

2023-01-27 16:55 UTC, alebrigant commented on geomstats/information_geometry/poisson.py
>                  Point representing an Poisson distribution (lambda).
Change to "Point in the sample space, i.e. an integer."

2023-01-27 21:22 UTC, alebrigant commented
@tramy1258 sorry last request: I didn't see it before but there are some remaining flake 8 errors (see Linting). Could you please fix these before the merge ? Almost there !

2023-01-28 14:19 UTC, tramy1258 commented
> @tramy1258 sorry last request: I didn't see it before but there are some remaining flake 8 errors (see Linting). Could you please fix these before the merge ? Almost there !

It is all done normally!

2023-01-28 17:07 UTC, merged