Refactor special_euclidean.py for _plotter.py and corrected import in _plotter.py
geomstats/geomstats pull request #1817
Opened 2023-01-31 01:51 UTC by SamFeinstein

## Checklist

- [ x] My pull request has a clear and explanatory title.
- [x ] If necessary, my code is [vectorized](https://www.geeksforgeeks.org/vectorization-in-python/).
- [x ] I added appropriate unit tests.
- [x ] I made sure the code passes all unit tests. (refer to comment below) (there seemed to be other unrelated errors?)
- [x ] My PR follows [PEP8](https://peps.python.org/pep-0008/) guidelines. (refer to comment below)
- [x ] My PR follows [geomstats coding style](https://github.com/geomstats/geomstats/blob/master/docs/contributing.rst#coding-style-guidelines) and API.
- [x ] My code is properly documented and I made sure the documentation renders properly. ([Link](https://github.com/geomstats/geomstats/blob/master/docs/contributing.rst#documentation))
- [x ] I linked to issues and PRs that are relevant to this PR.

## Description

## Issue

## Additional context

2023-01-31 02:04 UTC, SamFeinstein commented
Still some errors from files that others are refactoring.

2023-02-15 18:44 UTC, ninamiolane requested changes
@luisfpereira could you help me review this? Thnks!

2023-02-15 18:44 UTC, ninamiolane commented on geomstats/visualization/_plotting.py
> +import abc
Need docstring a the top of this file, see other geomstats' files for inspiration

2023-02-15 18:44 UTC, ninamiolane commented on geomstats/visualization/_plotting.py
> +class Plotter(metaclass=abc.ABCMeta):
Need docstring for the class and each of its method

2023-02-15 18:44 UTC, ninamiolane commented on geomstats/visualization/_plotting.py
> +        # TODO: points may need to be converted to numpy
Remove the two TODO lines

2023-02-15 18:44 UTC, ninamiolane commented on geomstats/visualization/hypersphere.py
> +class Circle(Plotter):
Nice!

2023-02-15 18:44 UTC, ninamiolane commented on geomstats/visualization/hypersphere.py
> +    def plot_space(self, ax=None, color="black", **plot_kwargs):
Need docstring

2023-02-15 18:44 UTC, ninamiolane commented on geomstats/visualization/special_euclidean.py
>  """Visualization for Geometric Statistics."""
Rename Visualization for special euclidean space

2023-02-15 18:44 UTC, ninamiolane commented on geomstats/visualization/hypersphere.py
> +class Sphere(Plotter):
Add method `plot_points`

2023-02-15 18:44 UTC, ninamiolane commented on geomstats/visualization/special_euclidean.py
> +    def __init__(self, point_type="matrix"):
missing plot_space
missing plot_points 
--> keep these two

2023-02-20 17:38 UTC, luisfpereira requested changes
@SamFeinstein, the plotter that you've created cannot be instantiated as you passed wrong arguments to `SpecialEuclidean`.

2023-02-20 17:38 UTC, luisfpereira commented on geomstats/visualization/_plotting.py
> +import geomstats._backend as gs
`geomstats.backend` is in fact the correct import.

2023-02-20 17:38 UTC, luisfpereira commented on geomstats/visualization/special_euclidean.py
> +        self._metric = SpecialEuclidean(point_a=[..., 2], point_b=[..., 2])
What's your purpose with these lines? They do not work.

2023-02-22 15:15 UTC, closed without merging