Alicehw1
geomstats/geomstats pull request #1819
Opened 2023-01-31 07:36 UTC by alicemo1

Changes made to hyperbolic.py file for homework 1.

## Checklist

- [ ] My pull request has a clear and explanatory title.
- [ ] If necessary, my code is [vectorized](https://www.geeksforgeeks.org/vectorization-in-python/).
- [ ] I added appropriate unit tests.
- [ ] I made sure the code passes all unit tests. (refer to comment below)
- [ ] My PR follows [PEP8](https://peps.python.org/pep-0008/) guidelines. (refer to comment below)
- [ ] My PR follows [geomstats coding style](https://github.com/geomstats/geomstats/blob/master/docs/contributing.rst#coding-style-guidelines) and API.
- [ ] My code is properly documented and I made sure the documentation renders properly. ([Link](https://github.com/geomstats/geomstats/blob/master/docs/contributing.rst#documentation))
- [ ] I linked to issues and PRs that are relevant to this PR.

## Description

## Issue

## Additional context

2023-02-15 19:04 UTC, ninamiolane requested changes
@luisfpereira

2023-02-20 17:51 UTC, luisfpereira requested changes
@alicemo1, several changes need to be done to make it consistent with `Plotter` class.

2023-02-20 17:51 UTC, luisfpereira commented on geomstats/visualization/hyperbolic.py
>              self.add_points(points)
one of the main ideas of `Plotter` is to not have state, i.e. `self.points` is to be removed. Therefore, this should be removed.

2023-02-20 17:51 UTC, luisfpereira commented on geomstats/visualization/hyperbolic.py
>          ax.scatter(points_x, points_y, **kwargs)
`plot_space` should be responsible to plot only "the space", without points. Here usually we mean some wireframe style plot.

`plot` receives `points` (check in `Plotter`) and is where points can actually be plotted.

2023-02-20 17:51 UTC, luisfpereira commented on geomstats/visualization/hyperbolic.py
>      def draw(self, ax, **kwargs):
this does not exist in `Plotter`.

2023-02-20 17:51 UTC, luisfpereira commented on geomstats/visualization/hyperbolic.py
>      def plot(self, points, ax=None, point_type=None, **point_draw_kwargs):
`point_type` should not be in signature, but at init.

2023-02-20 17:51 UTC, luisfpereira commented on geomstats/visualization/hyperbolic.py
>      def add_points(self, points):
to be removed.

2023-02-20 17:51 UTC, luisfpereira commented on geomstats/visualization/hyperbolic.py
>      def draw(self, ax, **kwargs):
as above.

2023-02-20 17:51 UTC, luisfpereira commented on geomstats/visualization/hyperbolic.py
>      def plot(self, points, ax=None, point_type=None, **point_draw_kwargs):
as above.

2023-02-22 15:14 UTC, closed without merging