Dynamic programming algorithm for computing distances and geodesics for the SRV metric
geomstats/geomstats pull request #1847
Opened 2023-05-04 15:13 UTC by Abdellaoui-Souhail

## Checklist

- [ ] My pull request has a clear and explanatory title.
- [ ] If necessary, my code is [vectorized](https://www.geeksforgeeks.org/vectorization-in-python/).
- [ ] I added appropriate unit tests.
- [ ] I made sure the code passes all unit tests. (refer to comment below)
- [ ] My PR follows [PEP8](https://peps.python.org/pep-0008/) guidelines. (refer to comment below)
- [ ] My PR follows [geomstats coding style](https://github.com/geomstats/geomstats/blob/master/docs/contributing.rst#coding-style-guidelines) and API.
- [ ] My code is properly documented and I made sure the documentation renders properly. ([Link](https://github.com/geomstats/geomstats/blob/master/docs/contributing.rst#documentation))
- [ ] I linked to issues and PRs that are relevant to this PR.

## Description

## Issue

## Additional context

2023-05-05 06:25 UTC, alebrigant requested changes
Here are a few first comments. I haven't looked at the tests yet, because most of them don't pass. 

An important issue is the organization of the code, which will be affected by the modifications made in https://github.com/luisfpereira/geomstats/pull/8#issuecomment-1522004958. @luisfpereira, should we maybe wait for your PR to pass before continuing on this ? This is a PR that implements another method to compute geodesics in the quotient space, when the total metric is the `SRVMetric`.

2023-05-05 06:25 UTC, alebrigant commented on geomstats/geometry/discrete_curves.py
> +
Missing docstring. What does this do ?

2023-05-05 06:25 UTC, alebrigant commented on geomstats/geometry/discrete_curves.py
> +            q = np.array([_q[int(np.floor(i * (k_sampling_point / n)))]
All the `np.` should be replaced by `gs.`

2023-05-05 06:25 UTC, alebrigant commented on geomstats/geometry/discrete_curves.py
> +            # Gamma's parameters
No inline comment.

2023-05-05 06:25 UTC, alebrigant commented on geomstats/geometry/discrete_curves.py
> +            """
Docstring should only be at the beginning of the method, not in the middle.

2023-05-05 06:25 UTC, alebrigant commented on geomstats/geometry/discrete_curves.py
> +                q_1, q_2, x_min, x_max, y_min, y_max):
What is the difference between this function and the previous one, and do both really need to be implemented here ? If there is one that is better than the other, the other should be removed.

2023-05-05 07:17 UTC, luisfpereira commented
@alebrigant, I think it is better to wait for the merge. It will not be a long wait though (I'm probably finishing it today or very beginning of next week).

2023-05-05 07:52 UTC, alebrigant commented
Ok makes sense. @Abdellaoui-Souhail I think it's still worth it, in the meantime, to address previous comments and work on the tests. This means less things to do later !

2023-05-12 14:56 UTC, alebrigant requested changes
Almost there ! Still a few comments.

2023-05-12 14:56 UTC, alebrigant commented on geomstats/geometry/discrete_curves.py
> +        end_srv@\gamma(t) = end_srv(\gamma(t))\cdot\lvert\gamma(t)\rvert^\frac{1}{2}
Maybe replace "\lvert\gamma(t)\rvert" by "| \gamma(t) |" which gives the same output in Latex but is more readable in the docstring ?

2023-05-12 14:56 UTC, alebrigant commented on geomstats/geometry/discrete_curves.py
> +
Could you add a reference to a paper where dynamic programming is explained ? Like it is done e.g. [here](https://github.com/geomstats/geomstats/blob/master/geomstats/geometry/discrete_curves.py#LL816C5-L816C15).

2023-05-12 14:56 UTC, alebrigant commented on geomstats/geometry/discrete_curves.py
>      def align(self, point, base_point, n_times=20, threshold=1e-3):
Now we have 2 methods to align two curves and compute horizontal geodesics: (1) iterative horizontal projection and (2) dynamic programming. We should be able to call either of these methods in `align`, as well as in `horizontal_geodesic`. So what I suggest is:
- Rename `horizontal_geodesic` to `_iterative_horizontal_projection`
- Create a new `horizontal_geodesic` that calls either `_dynamic_programming` or `_iterative_horizontal_projection`
- Add a `method` variable to `align` and call `horizontal_geodesic(method=method)`.

2023-05-12 14:56 UTC, alebrigant commented on geomstats/geometry/discrete_curves.py
> +    def geodesic(self, initial_point, end_point, method="horizontal projection",
"iterative horizontal projection"

2023-05-12 14:56 UTC, alebrigant commented on geomstats/geometry/discrete_curves.py
> +        elif method == "dynamic programming" :
`elif` is not necessary here: see DeepSource errors.

2023-05-12 14:56 UTC, alebrigant commented on geomstats/geometry/discrete_curves.py
> +        if method == "horizontal projection" :
"iterative horizontal projection"

2023-05-12 14:56 UTC, alebrigant commented on geomstats/geometry/discrete_curves.py
> +            else :
Same as above.

2023-05-12 14:56 UTC, alebrigant commented on geomstats/geometry/discrete_curves.py
> +        def reparametrization_curve(curve, gamma):
Maybe change to just `reparametrize(curve, gamma)` ?

2023-05-12 14:56 UTC, alebrigant commented on geomstats/geometry/discrete_curves.py
> +            """Compute end_curve reparametrized by gamma.
Reparametrize curve by gamma ?

2023-05-12 14:56 UTC, alebrigant commented on geomstats/geometry/discrete_curves.py
> +                return results
All of this code should be moved to `horizontal_geodesic`.

2023-05-12 14:56 UTC, alebrigant commented on geomstats/geometry/discrete_curves.py
> +        method : str, {"horizontal projection", "dynamic programming"}
"iterative horizontal projection"

2023-05-15 09:26 UTC, alebrigant requested changes
Thanks for the changes ! Could you address the final minor comments and then we can merge !

2023-05-15 09:26 UTC, alebrigant commented on geomstats/geometry/discrete_curves.py
> +        Mio, Washington & Srivastava, Anuj & Joshi, Shantanu. (2007).
Thanks for adding the reference. Could you just copy the style used in geomstats ? See [here](https://github.com/geomstats/geomstats/blob/master/geomstats/geometry/discrete_curves.py#LL816C5-L816C15).

2023-05-15 09:26 UTC, alebrigant commented on geomstats/geometry/discrete_curves.py
> +                "Method not implemented"
Maybe be more specific here: "The only methods implemented are iterative horizontal projection and dynamic programming."

2023-05-15 09:26 UTC, alebrigant commented on geomstats/geometry/discrete_curves.py
> +        else :
Unnecessary else after return.

2023-05-15 09:26 UTC, alebrigant commented on geomstats/geometry/discrete_curves.py
> +        else :
Unnecessary else after return.

2023-05-15 09:26 UTC, alebrigant commented on geomstats/geometry/discrete_curves.py
> +        else :
Unnecessary else after return.

2023-05-15 12:13 UTC, merged