Add invariant metric for positive lower triangular matrices
geomstats/geomstats pull request #1872
Opened 2023-06-28 15:24 UTC by olivierbisson

In this PR we implement an invariant metric for positive lower triangular matrices. Additionally, we endow the PositiveLowerTriangularMatrices with a LieGroup structure and a Lie algebra.

2023-06-28 15:26 UTC, luisfpereira commented
@ninamiolane, we've added the tests for the metric in the new framework. I think it is not relevant to add them in the previous one because this metrics only slightly changes the definition of the `inner_product_at_identity`.

2023-06-29 06:31 UTC, ninamiolane requested changes
Looking great! However, each new function needs to come with its tests. May I let you coordinate with @luisfpereira to add corresponding tests? Thanks!

2023-06-29 07:44 UTC, luisfpereira commented
@ninamiolane we are already coordinating. I've added tests for this in the new framework (everything works fine). I would say it is not worthy to add them in the current framework because we actually have a lot of tests for the `InvariantMetric` already, and this metric basic relies on those methods with a small variant on the `inner_product_at_identity` to cover the cases where the `matrix_mat_at_identity` is not diagonal.

Moreover, the method added to `LowerTriangularMatrices` is just due to the `inner_product_at_identity` of `InvariantMetric` and simply calls an already existing method with another name.

2023-07-10 12:28 UTC, luisfpereira approved these changes

2023-11-29 16:32 UTC, luisfpereira approved these changes

2023-11-29 17:10 UTC, merged