Add SymmetricHollowMatrices and corresponding permutation-invariant metric
geomstats/geomstats pull request #1949
Opened 2024-02-06 10:46 UTC by luisfpereira

This PR builds on top of #1946 to add the matrix vector space `SymmetricHollowMatrices` and a permutation-invariant metric on it `HollowMatricesPermutationInvariantMetric`.

It also fixes small inheritance issues in `geometry.base`. In particular, deletes an abstract method which is also defined at manifold level in order to allow proper multiple inheritance from `LevelSet` and `MatrixVectorSpace`.

This is a first step to bring in pullback metrics on `Cor+` via the off-log diffeomorphism.

NB: merging this PR before #1946 also merges it.

2024-02-08 16:39 UTC, ninamiolane requested changes
It's too hard for me to read the code without docstring. I'll let you add them, including parameter description, then I'll review!

2024-02-08 16:39 UTC, ninamiolane commented on geomstats/geometry/symmetric_matrices.py
> +    """Space of symmetric hollow matrices."""
Explain what is a "hollow" matrix in the docstring.

2024-02-08 16:39 UTC, ninamiolane commented on geomstats/geometry/symmetric_matrices.py
> +    """A permutation-invariant metric on the space of hollow matrices.
Also explain here what is a hollow matrix.

Parameter description missing

2024-02-08 16:39 UTC, ninamiolane commented on geomstats/geometry/symmetric_matrices.py
> +    def _check_params(space, alpha, beta, gamma):
Add docstring even for private functions, to help readability

2024-02-12 15:44 UTC, luisfpereira commented
@ninamiolane, I've updated the docstrings. Hopefully the code is easier to understand now.

2024-02-19 11:43 UTC, merged