Add method to change the lists in `scalar_product_metric.py`
geomstats/geomstats pull request #1964
Opened 2024-02-23 15:30 UTC by johnharveymath

This fixes #1760 

A new class method is added to `ScalarProductMetric` called `add_scaled_method` which allows the user to configure how a method from RiemannianMetric should be scaled.

The added feature does not seem amenable to unit testing, but the following code does demonstrate that it works:

```from geomstats import geomstats
from geomstats.geometry.scalar_product_metric import ScalarProductMetric
from geomstats.geometry.hypersphere import Hypersphere

sphere = Hypersphere(2)
point = sphere.random_point(1)
print(sphere.metric.injectivity_radius(point))

new_metric = 2.0 * sphere.metric
print(new_metric.injectivity_radius(point))

ScalarProductMetric.add_scaled_method('injectivity_radius', 'linear')
new_metric = 2.0 * sphere.metric
print(new_metric.injectivity_radius(point))```

This has output

Questions

Should we add a functionality to remove items from the lists or to restore the 'factory default'?
Are we happy with allowing methods which are not explicitly handled to just silently go through untransformed? Maybe we should at least log that it's happening?

## Checklist

- [ ] My pull request has a clear and explanatory title.
- [ ] If necessary, my code is [vectorized](https://www.geeksforgeeks.org/vectorization-in-python/).
- [ ] I added appropriate unit tests.
- [ ] I made sure the code passes all unit tests. (refer to comment below)
- [ ] My PR follows [PEP8](https://peps.python.org/pep-0008/) guidelines. (refer to comment below)
- [ ] My PR follows [geomstats coding style](https://github.com/geomstats/geomstats/blob/main/docs/contributing.rst#coding-style-guidelines) and API.
- [ ] My code is properly documented and I made sure the documentation renders properly. ([Link](https://github.com/geomstats/geomstats/blob/main/docs/contributing.rst#documentation))
- [ ] I linked to issues and PRs that are relevant to this PR.

## Description

## Issue

## Additional context

2024-02-28 17:55 UTC, luisfpereira requested changes
Thanks @johnharveymath!

The idea is very good. I'm just wondering if we can keep the previous function-based approach and add  a method called e.g. `register_scaled_method` that does exactly what `add_scaled_method` is doing, but in a more transparent way (by being outside of the class). Is there any technical reason for such a solution not work?

2024-02-29 14:40 UTC, luisfpereira commented
Exactly that @johnharveymath, very nice! 

I like your singleton class idea very much (even though threading is not necessarily something we care about). The other advantage of this strategy I can see is that everything becomes encapsulated in an object, so we know clearly where to look for. I sugggest to make this class private (`_ScaledMethodsRegistry`).

2024-03-01 11:08 UTC, johnharveymath commented
Here we go. It seemed to make sense to put `_get_scaling_factor` into the new class as well. Conceptually, this class now holds all information to do with which methods can be handled and how to handle them. I put `_RESERVED_NAMES` in here as well.
The result is that `ScalarProductMetric` now goes to `_Scaled_Methods_Registry` every time it wants to know anything about a method, either accessing one of its private methods or directly accessing its private variable `_RESERVED_NAMES`.
I'm not 100% of whether that's a nice structure.
Then, as for where the function `register_scaled_method` should go, I realised that we usually keep everything a little deep in the namespace and you have to go to the correct module to pull it out. Doing `from geomstats.geometry import register_scaled_method` would be a bit out of the ordinary. So it is going to be `from geomstats.geometry.scalar_product_metric import register_scaled_method`. I think that's fine, as it's not going to see a lot of use. I think the most use it will get will be internal. Once we're happy with this I can add it to a few classes where I see the need, either in this PR or in a new one.

2024-03-01 16:21 UTC, luisfpereira approved these changes
I think the design is very clean @johnharveymath. From my side we can merge as it it. (I suggest to register methods in another PR.)

2024-03-01 16:38 UTC, merged